# Generated by Django 4.2.4 on 2023-09-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_manufacturers_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='Country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='manufacturers',
            old_name='Country',
            new_name='country',
        ),
    ]
