# Generated by Django 4.2.4 on 2023-09-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_type_of_equipment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_of_equipment',
            new_name='EquipmentType',
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Страны', 'verbose_name_plural': 'Страны'},
        ),
    ]
