# Generated by Django 4.2.4 on 2023-09-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='article',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
