# Generated by Django 4.2.4 on 2023-09-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_equipment_article_equipment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='article',
            new_name='vendore_code',
        ),
    ]
