# Generated by Django 4.2.4 on 2023-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_article_equipment_vendore_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
