# Generated by Django 4.2.4 on 2023-10-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_equipment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
