# Generated by Django 4.2.4 on 2023-10-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_boxmaterial_alter_equipment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id_equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.equipment')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.boxmaterial')),
            ],
        ),
    ]
