# Generated by Django 4.2.4 on 2023-10-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='id_equipment',
            new_name='equipment',
        ),
    ]
