# Generated by Django 4.2.6 on 2023-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_boxip_box_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
