# Generated by Django 4.2.6 on 2023-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
