# Generated by Django 4.2.6 on 2023-12-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_city_name_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('patronymic', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=32)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company')),
            ],
        ),
    ]
