# Generated by Django 4.2.4 on 2023-12-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.companiesform'),
        ),
    ]
