# Generated by Django 4.2.6 on 2023-12-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_person_email_alter_person_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
