# Generated by Django 4.2.4 on 2023-12-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_company_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('serial_num', models.IntegerField()),
                ('project', models.CharField(max_length=32, null=True)),
                ('assembler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled_boxes', to='main.person')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company')),
                ('scheme_developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developed_boxes', to='main.person')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_boxes', to='main.person')),
            ],
        ),
    ]
