# Generated by Django 4.2.4 on 2023-12-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_boxaccounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxaccounting',
            name='programmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmer_boxes', to='main.person'),
        ),
    ]
