# Generated by Django 4.2.4 on 2023-12-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='serial',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
