# Generated by Django 4.2.4 on 2023-12-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxaccounting',
            name='customer',
        ),
    ]
