# Generated by Django 4.2.4 on 2023-12-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_boxaccounting_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxaccounting',
            name='serial_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order'),
        ),
    ]
