# Generated by Django 4.2.4 on 2023-12-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_boxaccounting_serial_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxaccounting',
            name='project',
        ),
        migrations.AddField(
            model_name='boxaccounting',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order'),
        ),
        migrations.AlterField(
            model_name='boxaccounting',
            name='serial_num',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
