# Generated by Django 4.2.4 on 2023-12-15 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_boxaccounting_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxaccounting',
            name='priority',
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
