# Generated by Django 4.2.6 on 2023-12-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxaccounting',
            name='serial_num',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vendore_code',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
