# Generated by Django 4.2.6 on 2023-12-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_order_id_alter_order_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box_Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('serial_num', models.IntegerField(unique=True)),
                ('assembler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled_boxes', to='main.person')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order')),
                ('programmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmer_boxes', to='main.person')),
                ('scheme_developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developed_boxes', to='main.person')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_boxes', to='main.person')),
            ],
        ),
        migrations.DeleteModel(
            name='BoxAccounting',
        ),
    ]
