# Generated by Django 4.2.6 on 2024-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_box_accounting_delete_boxaccounting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box_accounting',
            name='id',
        ),
        migrations.AlterField(
            model_name='box_accounting',
            name='serial_num',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
