# Generated by Django 4.2.6 on 2024-01-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_box_accounting_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box_accounting',
            old_name='order',
            new_name='order_id',
        ),
    ]
