# Generated by Django 4.2.6 on 2024-01-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rename_order_box_accounting_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Box_Accounting',
        ),
    ]
