# Generated by Django 4.2.6 on 2024-01-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_box_accounting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Box_Accounting',
        ),
    ]
