# Generated by Django 4.2.6 on 2024-01-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_delete_box_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box_Accounting',
            fields=[
                ('serial_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('assembler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled_boxes', to='main.person')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order')),
                ('programmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmer_boxes', to='main.person')),
                ('scheme_developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developed_boxes', to='main.person')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_boxes', to='main.person')),
            ],
        ),
    ]
