# Generated by Django 4.2.6 on 2024-01-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_box_accounting_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box_accounting',
            name='client',
        ),
    ]
