# Generated by Django 4.2.6 on 2024-01-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_remove_box_accounting_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
