# Generated by Django 4.2.6 on 2024-01-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box_accounting',
            name='assembler',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assembled_boxes', to='main.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box_accounting',
            name='name',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box_accounting',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box_accounting',
            name='scheme_developer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='developed_boxes', to='main.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box_accounting',
            name='tester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tested_boxes', to='main.person'),
            preserve_default=False,
        ),
    ]
