# Generated by Django 4.2.6 on 2024-01-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_box_accounting_assembler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box_accounting',
            name='serial_num',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
